### ISSUE TITLE
[Feature] 메뉴 생성 및 전체 품목 수량, 매출 출력문 작성

### ISSUE THREAD

**Issue by dmlwls12** [ssg-240304-java2/OOP-javaMart#6]
## 🔥 Description
메뉴 생성하고 전체 출력문 작성했습니다.

## 🔥To do
- [ ] 팀원들 코드 작성 후 마지막으로 출력문 수정

## 🔥 History
- 2024.04.03 : 메뉴 생성 및 출력문 작성 완료

**Comment by speter6501** [comment]
수고하셨습니다!
